/*
====================================================================================
Analytics Queries / Exploratory Data Analysis
====================================================================================

Purpose:
    - Explore the gold layer data warehouse and validate key business metrics.
    - Analyze customer, product, and sales performance.
    - Generate insights for reporting and dashboard development.

Sections:
    1. Database and schema exploration
    2. Data overview and validation
    3. Overall business KPIs
    4. Customer analysis
    5. Product analysis
    6. Top and bottom performers

====================================================================================
*/


/*
====================================================================================
1. Database and Schema Exploration
====================================================================================
*/

-- Review available tables and inspect column definitions
SELECT * 
FROM INFORMATION_SCHEMA.TABLES;

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'dim_customers';


USE datawarehouse;


/*
====================================================================================
2. Data Overview and Validation
====================================================================================
*/

-- Determine the sales data coverage period
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MAX(order_date), MIN(order_date)) AS total_days,
    TIMESTAMPDIFF(MONTH, MIN(order_date), MAX(order_date)) AS total_months
FROM gold_fact_sales;


-- Understand customer age distribution
SELECT 
    TIMESTAMPDIFF(YEAR, MIN(birthdate), NOW()) AS youngest_age,
    TIMESTAMPDIFF(YEAR, MAX(birthdate), NOW()) AS oldest_age
FROM gold_dim_customer;


-- Basic fact table measurements
SELECT SUM(sales_amount) AS total_sales 
FROM gold_fact_sales;

SELECT SUM(quantity) AS total_quantity 
FROM gold_fact_sales;

SELECT AVG(price) AS average_price 
FROM gold_fact_sales;

SELECT COUNT(order_number) AS total_orders 
FROM gold_fact_sales;

SELECT COUNT(DISTINCT order_number) AS unique_orders 
FROM gold_fact_sales;

SELECT COUNT(DISTINCT product_id) AS total_products
FROM gold_dimension_products;



/*
====================================================================================
3. Executive Business Metrics
====================================================================================
*/

-- Consolidated KPI overview for quick business reporting
SELECT 
    'TOTAL SALES' AS measure_name, 
    SUM(sales_amount) AS measure_value 
FROM gold_fact_sales

UNION ALL

SELECT 
    'TOTAL QUANTITY', 
    SUM(quantity) 
FROM gold_fact_sales

UNION ALL 

SELECT 
    'AVERAGE PRICE', 
    ROUND(AVG(price),0) 
FROM gold_fact_sales

UNION ALL

SELECT 
    'TOTAL ORDERS', 
    COUNT(DISTINCT order_number) 
FROM gold_fact_sales

UNION ALL

SELECT 
    'TOTAL PRODUCTS', 
    COUNT(product_name) 
FROM gold_dimension_products

UNION ALL 

SELECT 
    'TOTAL CUSTOMERS', 
    COUNT(customer_key) 
FROM gold_dim_customer;



/*
====================================================================================
4. Customer Analysis
====================================================================================
*/

-- Customer distribution by geographic and demographic attributes
SELECT 
    country, 
    COUNT(customer_id) AS customer_count
FROM gold_dim_customer
GROUP BY country;


SELECT 
    gender, 
    COUNT(customer_id) AS customer_count
FROM gold_dim_customer
GROUP BY gender;


-- Revenue contribution by customer
SELECT 
    c.customer_key,
    SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customer c
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key
ORDER BY revenue DESC;


-- Countries generating the highest quantity sales
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold_fact_sales f
LEFT JOIN gold_dim_customer c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;



/*
====================================================================================
5. Product Analysis
====================================================================================
*/

-- Product distribution across categories
SELECT 
    category,
    COUNT(product_id) AS product_count
FROM gold_dimension_products
GROUP BY category;


-- Average product cost by category
SELECT 
    category,
    ROUND(AVG(cost),0) AS average_cost
FROM gold_dimension_products
GROUP BY category;


-- Revenue generated by each product category
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dimension_products p
    ON p.product_key = f.product_key
GROUP BY p.category;



/*
====================================================================================
6. Product Performance Ranking
====================================================================================
*/

-- Top 5 products by revenue
SELECT 
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dimension_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;


-- Bottom 5 products by revenue
SELECT 
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dimension_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue
LIMIT 5;


-- Top performing subcategories
SELECT 
    p.subcategory,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dimension_products p
    ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC
LIMIT 5;


-- Ranking products using window functions
SELECT *
FROM
(
    SELECT 
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        ROW_NUMBER() OVER(
            ORDER BY SUM(f.sales_amount) DESC
        ) AS product_rank
    FROM gold_fact_sales f
    LEFT JOIN gold_dimension_products p
        ON p.product_key = f.product_key
    GROUP BY p.product_name
)t
WHERE product_rank <= 5;


-- Lowest performing subcategories
SELECT 
    p.subcategory,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dimension_products p
    ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue
LIMIT 5;



/*
====================================================================================
7. Customer Performance Ranking
====================================================================================
*/

-- Customers contributing the highest revenue
SELECT 
    c.customer_key,
    SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customer c
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key
ORDER BY revenue DESC
LIMIT 10;


-- Customers with the lowest purchase frequency
SELECT 
    c.customer_key,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold_fact_sales f
LEFT JOIN gold_dim_customer c
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key
ORDER BY total_orders
LIMIT 3;
